# -*- coding: utf-8 -*-
"""bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P48sYLF1fcL35zmjUbV5ApXkjczAimsD
"""

import alpaca_trade_api as tradeapi
import pandas as pd
import time
from datetime import datetime
import pytz
import csv
from ta.momentum import RSIIndicator
from ta.trend import SMAIndicator, MACD

# ===== CONFIG =====
API_KEY = "YOUR_API_KEY"
SECRET_KEY = "YOUR_SECRET_KEY"
BASE_URL = "https://paper-api.alpaca.markets"

# ===== STRATEGY SETTINGS =====
MAX_POSITIONS = 6

# ORIGINAL QC VALUES
SL = -0.01      # -1%
TP = 0.025      # +2.5%

# ===== UNIVERSE =====
UNIVERSE = [
    "AAPL","MSFT","NVDA","TSLA","AMD","META","AMZN","GOOGL",
    "NFLX","INTC","CSCO","ADBE","CRM","PYPL","AVGO","QCOM",
    "TXN","MU","BA","JPM","GS","MS","V","MA","DIS","WMT",
    "XOM","KO","PEP","SPY","QQQ","IWM","DIA"
]

# ===== INIT =====
api = tradeapi.REST(API_KEY, SECRET_KEY, BASE_URL)
eastern = pytz.timezone("US/Eastern")

symbols = []
last_universe_update = None

# ===== TRACKERS =====
traded_today = set()
current_day = None

# ===== PERFORMANCE =====
total_pnl = 0
trades = 0
wins = 0

# ===== CSV LOG =====
csv_file = "trades.csv"

with open(csv_file, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow([
        "Time",
        "Symbol",
        "Entry",
        "Exit",
        "PnL%"
    ])

# ===== DATA =====
def get_data(symbol):
    return api.get_bars(symbol, "1Min", limit=200).df

def compute_indicators(df):

    df['rsi'] = RSIIndicator(
        df['close'],
        window=7
    ).rsi()

    df['sma'] = SMAIndicator(
        df['close'],
        window=20
    ).sma_indicator()

    macd = MACD(df['close'])

    df['macd'] = macd.macd()
    df['signal'] = macd.macd_signal()

    return df

# ===== TOP VOLUME STOCKS =====
def get_top_stocks():

    vols = []

    for s in UNIVERSE:

        try:
            df = api.get_bars(
                s,
                "1Min",
                limit=30
            ).df

            if len(df) < 10:
                continue

            dollar_volume = (
                df['volume'].sum()
                * df.iloc[-1]['close']
            )

            vols.append((s, dollar_volume))

        except:
            continue

    vols.sort(
        key=lambda x: x[1],
        reverse=True
    )

    return [x[0] for x in vols[:30]]

# ===== SIGNAL =====
def get_signal(df):

    latest = df.iloc[-1]
    prev = df.iloc[-2]

    if (
        prev['rsi'] <= 55
        and latest['rsi'] > 55
        and latest['macd'] > latest['signal']
        and latest['close'] > latest['sma']
    ):

        score = (
            (latest['rsi'] - 55)
            + (latest['macd'] - latest['signal'])
        )

        return True, score

    return False, None

# ===== MAIN LOOP =====
while True:

    try:

        clock = api.get_clock()

        print("\n====================================")
        print(f"Time (ET): {clock.timestamp}")
        print(f"Market Open: {clock.is_open}")

        # ===== MARKET CLOSED =====
        if not clock.is_open:
            print("Market closed")
            time.sleep(60)
            continue

        now = datetime.now(eastern)

        # ===== RESET DAILY TRADED LIST =====
        today = now.date()

        if current_day != today:
            traded_today.clear()
            current_day = today
            print("New trading day - reset traded symbols")

        # ===== MORNING WINDOW ONLY =====
        if not (
            (now.hour == 9 and now.minute >= 30)
            or (now.hour == 10)
            or (now.hour == 11 and now.minute <= 30)
        ):
            print("Outside trading window")

        # ===== SYNC POSITIONS =====
        alpaca_positions = {
            p.symbol: p
            for p in api.list_positions()
        }

        # ===== PRINT POSITIONS =====
        print("\nCurrent Positions:")

        if not alpaca_positions:
            print("  None")

        else:
            for sym, pos in alpaca_positions.items():

                entry = float(pos.avg_entry_price)
                qty = int(pos.qty)
                pnl = float(pos.unrealized_plpc) * 100

                print(
                    f"{sym} | "
                    f"Qty {qty} | "
                    f"Entry {entry:.2f} | "
                    f"PnL {pnl:.2f}%"
                )

        # ===== UPDATE UNIVERSE =====
        if (
            last_universe_update is None
            or
            (datetime.now() - last_universe_update).seconds > 300
        ):

            symbols = get_top_stocks()
            last_universe_update = datetime.now()

            print("\nTop Stocks:")
            print(symbols)

        # ===== SCAN FOR ENTRIES =====
        candidates = []

        if (
            (now.hour == 9 and now.minute >= 30)
            or (now.hour == 10)
            or (now.hour == 11 and now.minute <= 30)
        ):

            for s in symbols:

                try:

                    # ===== DON'T TRADE SAME STOCK TWICE =====
                    if s in traded_today:
                        continue

                    # ===== SKIP CURRENT HOLDINGS =====
                    if s in alpaca_positions:
                        continue

                    df = get_data(s)

                    if len(df) < 50:
                        continue

                    df = compute_indicators(df)

                    price = df.iloc[-1]['close']

                    if price < 10:
                        continue

                    signal, score = get_signal(df)

                    if signal:
                        candidates.append(
                            (s, score, price)
                        )

                except:
                    continue

        # ===== SORT BEST SETUPS =====
        candidates.sort(
            key=lambda x: x[1],
            reverse=True
        )

        selected = candidates[:MAX_POSITIONS]

        # ===== BUY =====
        for s, score, price in selected:

            # Refresh live positions
            alpaca_positions = {
                p.symbol: p
                for p in api.list_positions()
            }

            # ===== MAX POSITIONS =====
            if len(alpaca_positions) >= MAX_POSITIONS:
                break

            # ===== SKIP IF ALREADY HELD =====
            if s in alpaca_positions:
                continue

            # ===== SKIP IF ALREADY TRADED TODAY =====
            if s in traded_today:
                continue

            account = api.get_account()

            # USING BUYING POWER (~200K)
            buying_power = float(account.buying_power)

            position_value = (
                buying_power / MAX_POSITIONS
            )

            qty = int(position_value / price)

            if qty <= 0:
                continue

            print(
                f"\nBUY {s} "
                f"@ {price:.2f} "
                f"| Qty {qty}"
            )

            try:

                api.submit_order(
                    symbol=s,
                    qty=qty,
                    side='buy',
                    type='market',
                    time_in_force='day'
                )

                # ===== ADD TO DAILY TRADED =====
                traded_today.add(s)

            except Exception as e:
                print("BUY ERROR:", e)

        # ===== EXIT LOGIC =====
        for s, pos in alpaca_positions.items():

            try:

                entry = float(pos.avg_entry_price)

                # LIVE PRICE
                price = api.get_latest_trade(s).price

                pnl = (
                    (price - entry)
                    / entry
                )

                # ===== QC SL / TP =====
                if pnl <= SL or pnl >= TP:

                    print(
                        f"\nSELL {s} "
                        f"@ {price:.2f} "
                        f"| PnL {pnl*100:.2f}%"
                    )

                    api.close_position(s)

                    # ===== STATS =====
                    total_pnl += pnl
                    trades += 1

                    if pnl > 0:
                        wins += 1

                    # ===== CSV LOG =====
                    with open(csv_file, "a", newline="") as f:

                        writer = csv.writer(f)

                        writer.writerow([
                            datetime.now(),
                            s,
                            entry,
                            price,
                            pnl * 100
                        ])

            except Exception as e:
                print("EXIT ERROR:", e)

        # ===== FORCE EXIT BEFORE CLOSE =====
        if now.hour == 15 and now.minute >= 45:

            print("\nFORCE EXIT ALL POSITIONS")

            for s in list(alpaca_positions.keys()):

                try:
                    api.close_position(s)
                    print(f"FORCE SELL {s}")

                except Exception as e:
                    print("FORCE EXIT ERROR:", e)

        # ===== PERFORMANCE =====
        if trades > 0:

            winrate = (
                wins / trades
            ) * 100

            print("\n===== PERFORMANCE =====")

            print(f"Trades: {trades}")
            print(f"Win Rate: {winrate:.2f}%")
            print(f"Total PnL: {total_pnl*100:.2f}%")

        print("\nLoop running...")
        print("====================================")

        time.sleep(3)

    except Exception as e:

        print("\nMAIN ERROR:", e)

        time.sleep(10)